version: '3'
services:
  nginx:
    ports:
      - "80:80"
  merin-app:
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    command: npm start