version: '3'
services:
  nginx:
    ports:
      - "80:80"
  merin-app:
    build: 
      context: .
      args: 
        NODE_ENV: production
    environment:
      - NODE_ENV=${NODE_ENV}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET }
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_CUSTOMER_ACCESS_SECRET=${JWT_CUSTOMER_ACCESS_SECRET }
      - JWT_CUSTOMER_REFRESH_SECRET=${JWT_CUSTOMER_REFRESH_SECRET}
      - PORT=${PORT}
      - VERIFICATION_CODE_EXP=${VERIFICATION_CODE_EXP}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT }
      - SMTP_SERVICE=${SMTP_SERVICE}
      - SMTP_MAIL=${SMTP_MAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID }
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - TRANSLATION_APIKEY=${TRANSLATION_APIKEY}
      - MONGO_DB_URI=${MONGO_DB_URI}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      - BUCKET_URL=${BUCKET_URL}
      - ORIGIN_ENDPOINT=${ORIGIN_ENDPOINT}
    command: npm start