import { config } from 'dotenv'
config();

export const local_config = {
NODE_ENV: process.env.NODE_ENV,
CLOUD_NAME: process.env.CLOUD_NAME,
CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
JWT_ACCESS_SECRET:process.env.JWT_ACCESS_SECRET ,
JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
JWT_CUSTOMER_ACCESS_SECRET:process.env.JWT_CUSTOMER_ACCESS_SECRET ,
JWT_CUSTOMER_REFRESH_SECRET: process.env.JWT_CUSTOMER_REFRESH_SECRET,
PORT: process.env.PORT,
VERIFICATION_CODE_EXP: process.env.VERIFICATION_CODE_EXP,
SMTP_HOST: process.env.SMTP_HOST,
SMTP_PORT:process.env.SMTP_PORT ,
SMTP_SERVICE: process.env.SMTP_SERVICE,
SMTP_MAIL: process.env.SMTP_MAIL,
SMTP_PASSWORD: process.env.SMTP_PASSWORD,
FIREBASE_PROJECT_ID:process.env.FIREBASE_PROJECT_ID ,
FIREBASE_PRIVATE_KEY: process.env.FIREBASE_PRIVATE_KEY,
FIREBASE_CLIENT_EMAIL: process.env.FIREBASE_CLIENT_EMAIL,
TRANSLATION_APIKEY: process.env.TRANSLATION_APIKEY,
MONGO_DB_URI:process.env.MONGO_DB_URI,
AWS_ACCESS_KEY_ID:process.env.AWS_ACCESS_KEY_ID,
AWS_SECRET_ACCESS_KEY: process.env.AWS_SECRET_ACCESS_KEY,
BUCKET_NAME: process.env.BUCKET_NAME,
BUCKET_URL: process.env.BUCKET_URL,
ORIGIN_ENDPOINT: process.env.ORIGIN_ENDPOINT,
}



